### PR TITLE
Added contribution information

### PR DESCRIPTION
**Pull request by lpulley**
Choose some things from this list to put yourself down for. Example:

@all-contributors add @lpulley for doc ideas review

### CODE REVIEW

**Comment by lpulley** [comment]
@all-contributors add @lpulley for doc ideas review

**Comment by lpulley** [comment]
See https://allcontributors.org/docs/en/emoji-key

**Comment by TejasQ** [comment]
@all-contributors add @tejasq for eventOrganizing ideas infra review test

**Comment by cjoshmartin** [comment]
@all-contributors add @cjoshmartin for code question bug doc maintenance

**Comment by cjoshmartin** [comment]
@all-contributors add @cjoshmartin for code question bug doc maintenance

**Comment by lpulley** [comment]
@all-contributors add @TejasQ for eventOrganizing ideas infra review test

**Comment by juancampa** [comment]
@all-contributors add @juancampa for eventOrganizing ideas infra review test

**Comment by cwlowder** [comment]
@all-contributors add @clowder2 for doc ideas bug code

**Comment by cwlowder** [comment]
@all-contributors add @cwlowder  for doc ideas bug code

**Comment by lpulley** [comment]
@allcontributors[bot] add @kmui2 for code review test

**Comment by lpulley** [comment]
@allcontributors[bot] add @rioam2 for code design bug test

**Comment by lpulley** [comment]
@all-contributors add @juancampa for eventOrganizing ideas infra review test

**Comment by lpulley** [comment]
@all-contributors add @juancampa for eventOrganizing ideas infra review test

**Comment by lpulley** [comment]
@all-contributors add @lpulley for doc ideas review
@all-contributors add @juancampa for eventOrganizing ideas infra review test
@allcontributors[bot] add @rioam2 for code design bug test
@allcontributors[bot] add @kmui2 for code review test
@all-contributors add @cwlowder for doc ideas bug code
@all-contributors add @cjoshmartin for code question bug doc maintenance
@all-contributors add @TejasQ for eventOrganizing ideas infra review test

**Comment by lpulley** [comment]
@all-contributors add @lpulley for doc ideas review

**Comment by lpulley** [comment]
@all-contributors add @juancampa for eventOrganizing ideas infra review test

**Comment by lpulley** [comment]
@allcontributors[bot] add @rioam2 for code design bug test

**Comment by lpulley** [comment]
@allcontributors[bot] add @kmui2 for code review test

**Comment by lpulley** [comment]
@all-contributors add @cwlowder for doc ideas bug code

**Comment by lpulley** [comment]
@all-contributors add @cjoshmartin for code question bug doc maintenance

**Comment by lpulley** [comment]
@all-contributors add @TejasQ for eventOrganizing ideas infra review test

**Pull request merged**
